name: RealityPhone
version: '1.0-SNAPSHOT'
main: me.dervinocap.originphone.RealityPhone
api-version: 1.19
commands:
  rephone:
  realityphone:
  chat-manage:
  emergency-respond:
  cabina-create:
  chats:
    aliases:
      - chat
      - c